### PR TITLE
Zarr backend

### PR DESCRIPTION
**Pull request by jhamman**
1. syncs with master
2. some cleanup
3. initial implementation of ZarrArrayWrapper

### CODE REVIEW

**Comment by rabernat** [comment]
This looks like it came off a pretty old branch. Tons of conflicts to resolve. How do you suggest I proceed?

**Comment by jhamman** [comment]
Grrr. Give me 2 minutes to sync. I'll ping you when its ready. I must have synced with my fork's zarr_backend branch.

**Comment by rabernat** [comment]
Note that I already implemented a `ZarrArrayWrapper` in https://github.com/pydata/xarray/pull/1528/commits/f39035cc4ff6eadc0fee1735d4e77939bd278624 and then updated it after rc1 in https://github.com/pydata/xarray/pull/1528/commits/e20c29f6c48ede025f75ceeddda0f4609a91a8b1.

**Comment by jhamman** [comment]
Yeah. This is pretty FUBAR at this point. I'm going to close this and start over. I know what I did.

**Pull request closed without merging**
